Update OCaml format
dialohq/stork pull request #27
Opened 2021-07-24 13:29 UTC by wokalski

2021-07-26 16:19 UTC, naartjie requested changes
I previously approved, but the build is failing.

2021-07-28 09:53 UTC, tsnobip approved these changes
lgtm now

2021-07-28 09:54 UTC, tsnobip commented
I also updated OCaml and OCaml LSP

2021-07-28 10:10 UTC, naartjie approved these changes

2021-07-28 11:41 UTC, merged